### ISSUE TITLE
Version tags on Docker hub

### ISSUE THREAD

**Issue by ruudud** [EventStore/eventstore-docker#1]
In addition to `latest` pointing to the latest stable release, version tags should exist.

The README should also follow the convention on listing available versions/tags and link to corresponding Dockerfile. See eg. the [Redis README](https://hub.docker.com/r/library/redis/) under _Supported tags and respective Dockerfile links_.

**Comment by shouze** [comment]
@ruudud I guess you can close this issue as from release 3.7 tagged container images are available on docker hub ;)

**Comment by pgermishuys** [comment]
@shouze thanks for reminding me! @ruudud please reopen if you feel any further work is necessary.
