### ISSUE TITLE
Can't run projections

### ISSUE THREAD

**Issue by drozzy** [EventStore/eventstore-docker#23]
My eventstore is not actually running projections. 

I am starting it with:

```
docker run --name eventstore-node -it -p 2113:2113 -p 1113:1113 -e EVENTSTORE_RUN_PROJECTIONS=all eventstore/eventstore
```

I also tried capital `All`.
But my projections still do not actually "run". I know this because my Recently Created Streams is empty in the UI, as well as my projection's last position and checkpoint are both `$ce-bee: -1`. 

When I run a standalone (non-docker) version with the following command, everything works as expected:

`sh run-node.sh --run-projections=all --start-standard-projections`

P.S.: Start `--start-standard-projections` is also not available in docker it seems, but I'm not sure if that has anything to do with it.

**Comment by drozzy** [comment]
Ok... this works:

```
docker run --name eventstore-node -it -p 2113:2113 -p 1113:1113 -e EVENTSTORE_RUN_PROJECTIONS=all -e EVENTSTORE_START_STANDARD_PROJECTIONS eventstore/eventstore
```

But here http://docs.geteventstore.com/server/3.5.0/command-line-arguments/ it says that "standard projections" is for development only.. yet without this argument, my projections don't run.

I'm a bit confused here. I guess I'll leave that in for now.

**Comment by pgermishuys** [comment]
The documentation was incorrect and was fixed in the following PR: https://github.com/EventStore/docs.geteventstore.com/pull/214.
