### ISSUE TITLE
How to set a custom EXT_HTTP_PORT?

### ISSUE THREAD

**Issue by bmmpt** [EventStore/eventstore-docker#33]
If I map the port with -p 4445:2113, the events I read from the store come back with port 2113.
I need the mapping to be 4445:4445, and the events I read to come back with links to 4445.

I was attempting to configure a different port to access the event store, but it doesn't seem to work. Does it look correct below?

docker run --name axon-eventstore-node -it -p 4445:4445 -p 1113:1113  -e EXT_HTTP_PORT=4445 eventstore/eventstore

Bruno

**Comment by charlessolar** [comment]
This is an old issue but I was toying with docker and it took me a couple hours to figure out environment variables must be prefixed with `EVENTSTORE_`

So the proper command for you would be

```
docker run --name axon-eventstore-node -it -p 4445:4445 -p 1113:1113 -e EVENTSTORE_EXT_HTTP_PORT=4445 eventstore/eventstore
```

Its mentioned in the docs - but I tend to not read table headers 🤦‍♂️

**Comment by arwinneil** [comment]
Hello,

This issue has been close due to management of Docker builds moving to [EventStore/EventStore](https://github.com/EventStore/EventStore) and this repository is due to be archived. If you are still experiencing this issue, please re-open this issue in the new repository.

Thank you.
