### ISSUE TITLE
Mounting volumes

### ISSUE THREAD

**Issue by BoasE** [EventStore/eventstore-docker#42]
Is there an example on binding logs and folders of a local drive ? Anyone tried so far?

**Comment by brown-m** [comment]
@BoasE better late than never...

I had no issues volume mounting, below command worked a treat

```docker run --name eventstore -dt -p 2113:2113 -p 1113:1113 -v /host/path/eventstore/data:/var/lib/eventstore -v /host/path/eventstore/log:/var/log/eventstore eventstore/eventstore:release-4.0.3```

**Comment by Industrial** [comment]
Maybe this info should also be put in the Readme. I was looking for this, and found it here :-)

**Comment by arwinneil** [comment]
Hello,

This issue has been closed due to management of Docker builds moving to [EventStore/EventStore](https://github.com/EventStore/EventStore), and this repository is due to be archived. If you are still experiencing this issue, please re-open this issue in the new repository.

Thank you.
