### ISSUE TITLE
--network alias key value pair is not a valid service argument

### ISSUE THREAD

**Issue by kry496** [EventStore/eventstore-docker#44]
Unable to set network alias for cluster mode that is later used part of the DNS variable

**Comment by arwinneil** [comment]
Hello,

This issue has been closed due to management of Docker builds moving to [EventStore/EventStore](https://github.com/EventStore/EventStore), and this repository is due to be archived. If you are still experiencing this issue, please re-open this issue in the new repository.

Thank you.
