### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by drozzy** [EventStore/eventstore-docker#55]
I'm running ES in docker container (using your official image) and get this error in my logging service.

Some facts:

- I am running ES on a VM (DigitalOcean's droplet) with 1GB max memory
- I am running ES in docker container

```
ApplicationName='df', CommandLine='-P /var/lib/eventstore', CurrentDirectory='', Native error= Out of memory
```

I am getting hundreds of these errors per hour now!

**Comment by drozzy** [comment]
This issue in Eventstore repo says it might be old version of Mono:

https://github.com/EventStore/EventStore/issues/1481

Is there anywhere where Mono is specified? I can't seem to find it.

**Comment by drozzy** [comment]
It seems you guys are using default mono version from Ubuntu 16.04.

Is it Mono 4.2 that comes with it? Any way to bump it to 4.8?

**Comment by shaan1337** [comment]
@drozzy please see my response on #1481: https://github.com/EventStore/EventStore/issues/1481#issuecomment-418173013

**Comment by arwinneil** [comment]
Hello,

This issue has been close due to management of Docker builds moving to [EventStore/EventStore](https://github.com/EventStore/EventStore), and this repository is due to be archived. If you are still experiencing this issue, please re-open this issue in the new repository.

Thank you.
