### ISSUE TITLE
Parameterize dockerfile 

### ISSUE THREAD

**Issue by dasjestyr** [EventStore/eventstore-docker#56]
RE: https://groups.google.com/forum/#!topic/event-store/Bxc8uX3eOV8

It would be a good addition to parameterize the Dockerfile so that release betas, release candidates, and new releases, etc. can be dockerized quicker. I recently went through and created my own image for the 5.0rc and it wasn't difficult, I only had to change a couple variables in the setup script to point to the new version numbers. The convention in there seems like it's almost consistent enough to parameterize. The end result might looks something like:

`docker build -t eventstore/eventstore:5.0-rc --build-arg VERSION=5.0rc --build-arg CHANNEL=prerelease .`

you get the idea...

**Comment by arwinneil** [comment]
Hello,

This issue has been closed due to management of Docker builds moving to [EventStore/EventStore](https://github.com/EventStore/EventStore), and this repository is due to be archived. 

Thank you.
