### ISSUE TITLE
What should be the memory usage when idle?

### ISSUE THREAD

**Issue by frederiksf** [EventStore/eventstore-docker#63]
What should be the memory usage when idle? On our kubernetes cluster we see a memory usage of 580 MB direct from start but with Docker-Compose on Windows a usage of 100 MB. 

Container:
  eventstore/eventstore:release-5.0.1

Env:
  EVENTSTORE_INT_IP: 0.0.0.0
  EVENTSTORE_EXT_IP: 0.0.0.0
  EVENTSTORE_RUN_PROJECTIONS: None
  EVENTSTORE_START_STANDARD_PROJECTIONS: "False"
  EVENTSTORE_EXT_TCP_HEARTBEAT_INTERVAL: "40000"
  EVENTSTORE_EXT_TCP_HEARTBEAT_TIMEOUT: "20000"
  EVENTSTORE_INT_TCP_HEARTBEAT_INTERVAL: "40000"
  EVENTSTORE_INT_TCP_HEARTBEAT_TIMEOUT: "20000"
  EVENTSTORE_DB: /db
  EVENTSTORE_LOG: /db
  EVENTSTORE_CHUNKS_CACHE_SIZE: "67108928"
 
Has this something todo with server/desktop garbage collection settings.

**Comment by frederiksf** [comment]
Anyone?

**Comment by gregoryyoung** [comment]
by default 2 chunks will be cached in memory ...

See CACHED_CHUNKS

Note that you likely *want* this memory used.

**Comment by arwinneil** [comment]
Hello,

This issue has been close due to management of Docker builds moving to [EventStore/EventStore](https://github.com/EventStore/EventStore), and this repository is due to be archived.

Thank you.
