### ISSUE TITLE
No image available for the 5.0.2 release

### ISSUE THREAD

**Issue by baronfel** [EventStore/eventstore-docker#65]
I was looking for 5.0.2 as I was updating testing environments at work and was surprised to see that it didn't exist yet. Anything we can do to help make that happen?

**Comment by arwinneil** [comment]
Link to image on DockerHub : [eventstore/eventstore:5.0.2-xenial](https://hub.docker.com/layers/eventstore/eventstore/5.0.2-xenial/images/sha256-99f8977045ffd44ddfcd4db8d948c1622865a60245c8b2998f1beae55eaa411a?context=repo)
