### ISSUE TITLE
Why hosting docker build script externaly and no on this repository?

### ISSUE THREAD

**Issue by shouze** [EventStore/eventstore-docker#8]
Seen in [Dockerfile](https://github.com/EventStore/eventstore-docker/blob/f49b40a13986438a93cc385e3cbdd31ed7ced58f/Dockerfile):

https://packagecloud.io/install/repositories/EventStore/EventStore-OSS/script.deb.sh

**Comment by pgermishuys** [comment]
The script you are referring to isn't owned by us. The docker image installs Event Store from package cloud.
