### ISSUE TITLE
web admin ui inaccessible

### ISSUE THREAD

**Issue by markglibres** [EventStore/eventstore-docker#80]
with the latest docker image, web admin ui seems to be inaccessible

"This site can’t be reached"..

older versions seems to work (eventstore/eventstore:release-5.0.8)

**Comment by YoEight** [comment]
Hi @markglibres,

Did you make sure you use `https` to target the web UI? I suspect you used `http` instead.

**Comment by edg-jf** [comment]
Same issue here... not working for both http and https

I ran the following docker commands with **_no_** errors displayed:

```
> docker pull eventstore/eventstore

> docker images
   Result:   eventstore/eventstore        latest      0c522f967516    2 weeks ago    394MB

> docker run --name eventstore-node -it -p 2113:2113 -p 1113:1113 eventstore/eventstore --dev

> docker inspect -f "{{ .NetworkSettings.IPAddress }}" eventstore-node
   Result: 172.x.x.x
```

Then I tried the following URLs in a browser with no success (Error is: ERR_CONNECTION_TIMED_OUT): 
- http://172.17.0.2:2113 
- https://172.17.0.2:2113

Note: I am on a Windows 10 OS (Build 1909)
Note2: As mentionned by @markglibres, my same steps worked with release-5.0.8

**Comment by YoEight** [comment]
Hello @frenchyjef,

I just did the following and I can reach out the web UI no problem:

```
docker run --name eventstore-node -it -p 2113:2113 -p 1113:1113 -e EVENTSTORE_DEV=true eventstore/eventstore:20.6.0-bionic
```

I think your issue was how you tried to enable the dev mode (I'm using the same docker image as you)

**Comment by YoEight** [comment]
I tried it on my personal computer so I was able to access the UI through `https://localhost:2113`

**Comment by markglibres** [comment]
> Hi @markglibres,
> 
> Did you make sure you use `https` to target the web UI? I suspect you used `http` instead.

I tried both.. I also tried with dev mode and not, still nothing.. and I used the latest image without tag eventstore/eventstore

**Comment by YoEight** [comment]
@markglibres did you try what I posted here: https://github.com/EventStore/eventstore-docker/issues/80#issuecomment-651558710? Because I have no problem reaching the web UI with it. Please post what you did otherwise.

**Comment by pabSec** [comment]
Using the approach proposed by @YoEight and using https should work but you have to tag it with `20.6.0-bionic`.

If you use the latest tag the image apparently runs without accessing connections from outside the container.

**Comment by pabSec** [comment]
Build the image locally, there must be some errors in the one pushed to docker hub.

`docker build https://github.com/EventStore/eventstore-docker.git`

**Comment by YoEight** [comment]
I managed to make it work as mentioned in comment https://github.com/EventStore/eventstore-docker/issues/80#issuecomment-651558710, with the same image mentioned in docker hub

**Comment by markglibres** [comment]
yep, the one with tag worked... hope the latest image on the docker repo will be fixed.  (which was the issue of this ticket)

**Comment by pgermishuys** [comment]
Hi @markglibres, we have updated the latest image to that of the bionic image. Would you mind confirming that it works for you now?
If this doesn't work, would you mind posting your configuration?

**Comment by markglibres** [comment]
> Hi @markglibres, we have updated the latest image to that of the bionic image. Would you mind confirming that it works for you now?
> If this doesn't work, would you mind posting your configuration?

thanks @pgermishuys , worked like a charm!

**Comment by pgermishuys** [comment]
That's good news! Thanks @markglibres.
I am going to close this issue. Please don't hesitate to reach out if you experience any further issues.
