### ISSUE TITLE
Alpine linux lightweight variant

### ISSUE THREAD

**Issue by shouze** [EventStore/eventstore-docker#9]
Is eventstore compatible with [libmusl](http://www.musl-libc.org/)?

**Comment by pgermishuys** [comment]
We have discussed possibly using alpine linux for the container, will need to do some investigation into this one. Will note it and add to backlog.

Unfortunately don't know the answer offhand.

**Comment by stefc** [comment]
I would also like a very lightweight docker container for the event-store!

**Comment by shouze** [comment]
Ok as alpine is based on libmusl... that's [not well supported by mono ATM](http://www.mono-project.com/docs/about-mono/releases/4.0.0/#musl-libc) so the timing is not good, should wait and see.

**Comment by enumag** [comment]
Apparently EventStore 6.0 no longer requires Mono. Perhaps this opens a way for an alpine-based image now?

https://eventstore.com/blog/event-store-6.0.0-preview-release/#mono-is-no-longer-required

**Comment by shouze** [comment]
worth to give a try indeed

**Comment by arwinneil** [comment]
Hello,

This issue has been close due to management of Docker builds moving to EventStore/EventStore, and this repository is due to be archived. If you are still experiencing this issue, please re-open this issue in the new repository.

Thank you.
